--- #YAML:1.0
name:                HTML-BBCode
version:             2.04
abstract:            Perl extension for converting BBcode to HTML.
license:             ~
author:              
    - M. Blom <blom@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    HTML::StripScripts:            1.04
    HTML::StripScripts::Parser:    0
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
