--- #YAML:1.0
name:                HTML-BBCode
version:             2.01
abstract:            Perl extension for converting BBcode to HTML.
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    HTML::StripScripts:            1.04
    HTML::StripScripts::Parser:    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - M. Blom <blom@cpan.org>
